name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: deploy page
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: cd vue/minesweeper && yarn --pure-lockfile
      - name: build
        run: cd vue/minesweeper && yarn build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./vue/minesweeper/dist
